### ISSUE TITLE
Update dialog unreadable

### ISSUE THREAD

**Issue by unodgs** [hiberbee/jetbrains-ide-theme#18]
![image](https://user-images.githubusercontent.com/7407/80524610-2d81d200-8990-11ea-9668-558dbb2ce49f.png)

I like the theme a lot but this one place seems to be not working :)

**Comment by vladyslavvolkov** [comment]
Hi, @unodgs 
Yeah, I have this issue in backlog, it happens occasionally, thats making it hardly reproducible. Will prioritize then and publish fix soon.
