### ISSUE TITLE
scheme did not apply

### ISSUE THREAD

**Issue by igorshelopaev** [Hiberbee/jetbrains-ide-theme#21]
I set up plugin, rebooted but nothing changed, scheme did not apply Do I need some extra settings? Idea 2019.3

**Comment by vladyslavvolkov** [comment]
@igorshelopaev could you check, please, is theme available in [File | Settings | Appearance & Behavior | Appearance](jetbrains://idea/settings?name=Appearance+%26+Behavior--Appearance) and [File | Settings | Editor | Color Scheme](jetbrains://idea/settings?name=Editor--Color+Scheme)?

**Comment by igorshelopaev** [comment]
Thank`s it works
Actually I expected that all setting would be automatically set up
May be it`s a good idea to add some description to plugin page "after setting plugin go to Color Scheme and pick up Hider be" if there`s no such information
