### ISSUE TITLE
Different color highlighting on autocomplete

### ISSUE THREAD

**Issue by gvammer** [hiberbee/jetbrains-ide-theme#22]
Default autocomplete selection is lighter than further ones.
It's confusing when working fast:(

![image](https://user-images.githubusercontent.com/2399223/85167027-d81bc000-b270-11ea-9368-2392f09d0eea.png)
![image](https://user-images.githubusercontent.com/2399223/85167048-de11a100-b270-11ea-9bb3-753d6fe528fa.png)

**Comment by vladyslavvolkov** [comment]
Hi, @gvammer 

As I remember, there is a special inactive state for this autocomplete. If I'm correct, those changes added should resolve this issue in 2.0.1 version. If not, give me please some extra details on that completion popup

**Comment by vladyslavvolkov** [comment]
@gvammer does issue still make sense?
