### ISSUE TITLE
Syntax Highlight in Scala Import statements not working with Hiberbee theme

### ISSUE THREAD

**Issue by nullptr7** [hiberbee/jetbrains-ide-theme#25]
**Describe the bug**

**To Reproduce**
1. Open a scala project
2. Import any class, trait, object you want to use
3. The color of those import statement is dark grey (giving an illusion that it is not used, though I am using it)
4. Attaching Screenshots

**Expected behavior**
It should have color convention similar to what we have in Java

**Screenshots**
![image](https://user-images.githubusercontent.com/54230460/91417337-3e731f00-e86e-11ea-8a5e-c40988a031ee.png)

IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 25, 2020
Licensed to IntelliJ IDEA Evaluator
Expiration date: September 20, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1967M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, com.hiberbee.intellij.hiberbee-theme, Lombook Plugin, com.mallowigi, org.jetbrains.kotlin, org.intellij.scala

**Comment by nullptr7** [comment]
Any update on this issue. I really love the theme but it doesn't look pleasing while looking at the imports...

**Comment by vladyslavvolkov** [comment]
@nullptr7 sorry for late response, was out of working activities.
This "bug" is persistent not only with Scala, but with Groovy and Kotlin as well. Their imports recognized differently than Java in IDEs. I will try to reach Jetbrains community for assistance, as have no ideas so far. Will keep you posted

**Comment by nullptr7** [comment]
@VladyslavVolkov I believe the latest release of this theme fixes the issue. :)
