### ISSUE TITLE
"#" in XML is Highlighted as Comments

### ISSUE THREAD

**Issue by YoussefRaafatNasry** [hiberbee/jetbrains-ide-theme#26]
In XML files, especially ones where the `#` symbol is used regularly like the `colors.xml` file in android, the symbol `#` makes line highlighted as comments instead of regular XML highlighting.

| Actual                                                                                                         | Expected _("#" removed to show the expected behaviour)_                                              |
|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/41103290/91579514-07733b00-e94c-11ea-88a6-277f9f93e535.png) | ![image](https://user-images.githubusercontent.com/41103290/91579689-473a2280-e94c-11ea-9404-a08ca9e7a166.png) |

 - OS: Windows
 - IDE: Android Studio
 - Theme Version: 2.0.1

**Comment by vladyslavvolkov** [comment]
@YoussefRaafatNasry is that issue still exist? Seems like duplicate #39 which I've commented already
