### ISSUE TITLE
could you please add the function which has seemed to be disabled in the newest version

### ISSUE THREAD

**Issue by joyment2010** [hiberbee/jetbrains-ide-theme#36]
**Describe the bug**
firstly, ths for your theme, it's really cool.
since I updated, the below function has disappeared.
![image](https://user-images.githubusercontent.com/30851677/111467632-9c5e4a00-875f-11eb-8c77-1dbc648a1a21.png)
![image](https://user-images.githubusercontent.com/30851677/111467687-b0a24700-875f-11eb-9b1d-2291d276deb3.png)

**Comment by vladyslavvolkov** [comment]
Actually, that is IDE setting - check please in **Editor > General > Breadcrumbs**

**Comment by joyment2010** [comment]
thank you, i also have realized it.
Appreciate your hiberbee plugin, and I has been using it everyday. May you a good day.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hiberbee/jetbrains-ide-theme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 凌晨3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hiberbee/jetbrains-ide-theme] could you please add the function which has seemed to be disabled in the newest version (#36)





 
Actually, that is IDE setting - jetbrains://AndroidStudio/settings?name=Editor--General--Breadcrumbs check please in Editor &gt; General &gt; Breadcrumbs
