### ISSUE TITLE
Android Studio have BUG

### ISSUE THREAD

**Issue by QJJXK555** [hiberbee/jetbrains-ide-theme#39]
![image](https://user-images.githubusercontent.com/57562593/119260167-2a452e00-bc04-11eb-906a-ac3eb0098a0d.png)
The color is displayed incorrectly in res/values/color.xml in Android Studio, and the color when selected is not obvious. Hope it can be fixed

**Comment by vladyslavvolkov** [comment]
@QJJXK555 is that issue still exist? Can't reproduce on latest 2022 Android Studio

**Comment by vladyslavvolkov** [comment]
Oh, actually I found the reason - Android Studio overrides XML formatting options

File | Settings | Editor | Code Style | XML

**Comment by vladyslavvolkov** [comment]
Yep, after checking out - seems like I am not able to control that part. That glitch relies only on that specific file, which override coloring scheme with color hashes from value. If you replace #FFBB86FC in your value with something invalid or just erase it - scheme applies properly.

I will communicate support on that question, so far - can't fix, unfortunatelly.
