### ISSUE TITLE
Change the tab font color to make the file name clear

### ISSUE THREAD

**Issue by lyudmilalala** [hiberbee/jetbrains-ide-theme#50]
Love this theme. Thanks to all you guys' work.

After the updates on 2021.8.1, the font color turns black when a tab is chosen/active, which makes the word on the tab unclear when it is hovered, as the background color is also pretty dark when hover. (I do not remember whether this happens before the current version. )

![1](https://user-images.githubusercontent.com/32922504/129293880-d2a3dc0e-f6b3-4fab-a9e3-e83b6592ecc4.png)
![image](https://user-images.githubusercontent.com/32922504/129293919-2718b407-0634-47a4-ba7c-bd583ca04656.png)

Maybe we could use a brighter color for the chosen/active tab, so it can be seen more clearly.

**Comment by wayneliu91** [comment]
I have the same problem.

**Comment by vladyslavvolkov** [comment]
Hi, thanks for feedback.

Published fix for that, should be available in day or so.

**Comment by alexbeewise** [comment]
Hello, @VladyslavVolkov 
the fix in the last release `2021.6.9.1041` hasn't solved the problem. The file name on the tab now looks like in the picture below.  Consider a resolution of at least FHD and some distance to the monitors, the file name is almost invisible.


![image](https://user-images.githubusercontent.com/99261199/164966662-b3e91077-875b-4d5b-8168-74799bf1a5a5.png)
